INSERT INTO `user` (`id`, `genero`, `email`, `nome`, `sobrenome`) VALUES
	(2, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(3, 'Masculino', 'EduardoC@gmail.com', 'Eduardo', 'Costa'),
	(6, 'Masculino', 'EduardoSilva@gmail.com', 'Eduardo', 'Silva de Oliveira'),
	(7, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(9, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(10, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(11, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(12, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(14, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(15, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(16, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(17, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(18, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(19, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(20, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(21, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(22, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(23, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(24, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva'),
	(25, 'Masculino', 'EduardoS@gmail.com', 'Eduardo', 'Silva');
